### ISSUE TITLE
Знайти фото Жидачева в Інтернеті

### ISSUE THREAD

**Issue by vikazagorbenska** [vikazagorbenska/pr4_2022#1]
Знайти найкраще фото в Інтернеті

**Comment by MariiaHuchko** [comment]
Вже шукаю

**Comment by MariiaHuchko** [comment]
![image](https://user-images.githubusercontent.com/117088181/199016092-61858be8-f50d-44b7-a870-cd5296946826.png)

**Comment by MariiaHuchko** [comment]
![image](https://user-images.githubusercontent.com/117088181/199016589-0abdb0b9-e5e0-41a0-a0f0-e91ee42c7b84.png)

**Comment by MariiaHuchko** [comment]
Зображення знайдено

**Comment by vikazagorbenska** [comment]
Завдання виконано
